version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eureka_blogs
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: eureka_blogs
      JWT_SECRET: eureka_blogs_jwt_secret
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://api:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql-data:
